ARCHIVO_EMISIONES_CO2 = "emisiones_co2.csv"
ARCHIVO_ENERGIAS_RENOVABLES = "energias_renovables.csv"

COLUMNA_CODIGOS_PAISES = 'Country Code'
COLUMNA_NOMBRES_PAISES = 'Country Name'

ARCHIVO_CODIGOS_PAISES = "codigos_paises.csv"
ARCHIVO_CODIGOS_PAISES_COLUMNA_CODIGOS = "alpha-3"

# ARCHIVO_ENERGIAS_RENOVABLES = "energias_renovables.csv" -- Está 2 veces

ULTIMO_ANIO_DISPONIBLE = "2019"
LAST_FIVE_YEARS = ["2015", "2016", "2017", "2018", "2019"]