ARCHIVO_EMISIONES_CO2 = "emisiones_co2.csv"
ARCHIVO_EMISIONES_CO2_COLUMNA_CODIGOS_PAISES = 'Country Code'
ARCHIVO_EMISIONES_CO2_COLUMNA_NOMBRES_PAISES = 'Country Name'

ARCHIVO_ENERGIAS_RENOVABLES = "energias_renovables.csv"
ARCHIVO_ENERGIAS_RENOVABLES_CODIGO_PAIS = "Country Name"

ARCHIVO_CODIGOS_PAISES = "codigos_paises.csv"
ARCHIVO_CODIGOS_PAISES_COLUMNA_CODIGOS = "alpha-3"

ULTIMO_ANIO_DISPONIBLE = "2019"